//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VendorSystem.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising.
        /// </summary>
        public static string Advertising {
            get {
                return ResourceManager.GetString("Advertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation.
        /// </summary>
        public static string Allocation {
            get {
                return ResourceManager.GetString("Allocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics Dashboard.
        /// </summary>
        public static string AnalyticsDashboard {
            get {
                return ResourceManager.GetString("AnalyticsDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annually.
        /// </summary>
        public static string Annually {
            get {
                return ResourceManager.GetString("Annually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Roles.
        /// </summary>
        public static string AssignRoles {
            get {
                return ResourceManager.GetString("AssignRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarCode.
        /// </summary>
        public static string BarCode {
            get {
                return ResourceManager.GetString("BarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Type.
        /// </summary>
        public static string CalculationType {
            get {
                return ResourceManager.GetString("CalculationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Registration.
        /// </summary>
        public static string CommercialRegistration {
            get {
                return ResourceManager.GetString("CommercialRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commerical Regester.
        /// </summary>
        public static string CommericalRegester {
            get {
                return ResourceManager.GetString("CommericalRegester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Code.
        /// </summary>
        public static string CompanyId {
            get {
                return ResourceManager.GetString("CompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name Eng.
        /// </summary>
        public static string CompanyNameEng {
            get {
                return ResourceManager.GetString("CompanyNameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Setting.
        /// </summary>
        public static string CompanySetting {
            get {
                return ResourceManager.GetString("CompanySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Settings.
        /// </summary>
        public static string CompanySettings {
            get {
                return ResourceManager.GetString("CompanySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensation.
        /// </summary>
        public static string Compensation {
            get {
                return ResourceManager.GetString("Compensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensation with growth percent.
        /// </summary>
        public static string CompensationGrowthPercent {
            get {
                return ResourceManager.GetString("CompensationGrowthPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactUs.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateNode {
            get {
                return ResourceManager.GetString("CreateNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer_ID.
        /// </summary>
        public static string Customer_ID {
            get {
                return ResourceManager.GetString("Customer_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Category.
        /// </summary>
        public static string CustomerCategory {
            get {
                return ResourceManager.GetString("CustomerCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Classification.
        /// </summary>
        public static string CustomerClassification {
            get {
                return ResourceManager.GetString("CustomerClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Code.
        /// </summary>
        public static string CustomerCode {
            get {
                return ResourceManager.GetString("CustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name Eng.
        /// </summary>
        public static string CustomerNameEng {
            get {
                return ResourceManager.GetString("CustomerNameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers Managment.
        /// </summary>
        public static string CustomersManagment {
            get {
                return ResourceManager.GetString("CustomersManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type.
        /// </summary>
        public static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date (From).
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date (To).
        /// </summary>
        public static string DateTO {
            get {
                return ResourceManager.GetString("DateTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you Want to Delete this?.
        /// </summary>
        public static string DeleteQuestion {
            get {
                return ResourceManager.GetString("DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        public static string Delivered {
            get {
                return ResourceManager.GetString("Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered Date.
        /// </summary>
        public static string DeliveredDate {
            get {
                return ResourceManager.GetString("DeliveredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delivered Quantity.
        /// </summary>
        public static string deliveredQty {
            get {
                return ResourceManager.GetString("deliveredQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display All Notifcations.
        /// </summary>
        public static string DisplayAllNotifcations {
            get {
                return ResourceManager.GetString("DisplayAllNotifcations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributor.
        /// </summary>
        public static string Distributor {
            get {
                return ResourceManager.GetString("Distributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributors.
        /// </summary>
        public static string Distributors {
            get {
                return ResourceManager.GetString("Distributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownLoad File.
        /// </summary>
        public static string DownLoadBtn {
            get {
                return ResourceManager.GetString("DownLoadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Current Status.
        /// </summary>
        public static string DownloadCurrentStatus {
            get {
                return ResourceManager.GetString("DownloadCurrentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Product Barcode List.
        /// </summary>
        public static string DownloadProductBarcodeList {
            get {
                return ResourceManager.GetString("DownloadProductBarcodeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Delivered Date.
        /// </summary>
        public static string ExpectedDeliveredDate {
            get {
                return ResourceManager.GetString("ExpectedDeliveredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Classification.
        /// </summary>
        public static string FirstClassification {
            get {
                return ResourceManager.GetString("FirstClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth.
        /// </summary>
        public static string Fourth {
            get {
                return ResourceManager.GetString("Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth Calssification.
        /// </summary>
        public static string FourthCalssification {
            get {
                return ResourceManager.GetString("FourthCalssification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Min Qty.
        /// </summary>
        public static string IsIncludeMinQty {
            get {
                return ResourceManager.GetString("IsIncludeMinQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Negative Sale.
        /// </summary>
        public static string IsNegativeSale {
            get {
                return ResourceManager.GetString("IsNegativeSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Barcode.
        /// </summary>
        public static string LargeBarcode {
            get {
                return ResourceManager.GetString("LargeBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Reference.
        /// </summary>
        public static string MainReference {
            get {
                return ResourceManager.GetString("MainReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture.
        /// </summary>
        public static string Manufacture {
            get {
                return ResourceManager.GetString("Manufacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        public static string Marketing {
            get {
                return ResourceManager.GetString("Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxQty.
        /// </summary>
        public static string MaxQty {
            get {
                return ResourceManager.GetString("MaxQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinQty.
        /// </summary>
        public static string MinQty {
            get {
                return ResourceManager.GetString("MinQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Qty %.
        /// </summary>
        public static string MinQtyPerpercentage {
            get {
                return ResourceManager.GetString("MinQtyPerpercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month Number.
        /// </summary>
        public static string MonthNumber {
            get {
                return ResourceManager.GetString("MonthNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name English.
        /// </summary>
        public static string NameEng {
            get {
                return ResourceManager.GetString("NameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Listing.
        /// </summary>
        public static string NewListing {
            get {
                return ResourceManager.GetString("NewListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Acount Not Related To Any Distributor And Will Not Be Able To Using This Screen.
        /// </summary>
        public static string NoDistributorForThisUser {
            get {
                return ResourceManager.GetString("NoDistributorForThisUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifcations.
        /// </summary>
        public static string Notifcations {
            get {
                return ResourceManager.GetString("Notifcations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Configuration.
        /// </summary>
        public static string OrderConfiguration {
            get {
                return ResourceManager.GetString("OrderConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Management.
        /// </summary>
        public static string OrderManagement {
            get {
                return ResourceManager.GetString("OrderManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Comments.
        /// </summary>
        public static string OtherComments {
            get {
                return ResourceManager.GetString("OtherComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Document Number.
        /// </summary>
        public static string PO_DocumentNumber {
            get {
                return ResourceManager.GetString("PO_DocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POs Configurations.
        /// </summary>
        public static string POsConfiguration {
            get {
                return ResourceManager.GetString("POsConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Product_Name {
            get {
                return ResourceManager.GetString("Product_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name in English.
        /// </summary>
        public static string Product_NameEn {
            get {
                return ResourceManager.GetString("Product_NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Category.
        /// </summary>
        public static string ProductsCategory {
            get {
                return ResourceManager.GetString("ProductsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion and Discounts.
        /// </summary>
        public static string PromotionDiscounts {
            get {
                return ResourceManager.GetString("PromotionDiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided By.
        /// </summary>
        public static string ProvidedBy {
            get {
                return ResourceManager.GetString("ProvidedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieved Date.
        /// </summary>
        public static string RecievedDate {
            get {
                return ResourceManager.GetString("RecievedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refrence Arabic Name.
        /// </summary>
        public static string RefrenceArName {
            get {
                return ResourceManager.GetString("RefrenceArName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refrence English Name.
        /// </summary>
        public static string RefrenceEnName {
            get {
                return ResourceManager.GetString("RefrenceEnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refrences.
        /// </summary>
        public static string Refrences {
            get {
                return ResourceManager.GetString("Refrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Date.
        /// </summary>
        public static string RejectedDate {
            get {
                return ResourceManager.GetString("RejectedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject The PO.
        /// </summary>
        public static string RejectPO {
            get {
                return ResourceManager.GetString("RejectPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReOrderQty.
        /// </summary>
        public static string ReOrderQty {
            get {
                return ResourceManager.GetString("ReOrderQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replenishment.
        /// </summary>
        public static string Replenishment {
            get {
                return ResourceManager.GetString("Replenishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replenishment Configuration.
        /// </summary>
        public static string ReplenishmentConfiguration {
            get {
                return ResourceManager.GetString("ReplenishmentConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replenish Management.
        /// </summary>
        public static string ReplenishmentManagement {
            get {
                return ResourceManager.GetString("ReplenishmentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replenishment Quantity.
        /// </summary>
        public static string ReplenishmentQty {
            get {
                return ResourceManager.GetString("ReplenishmentQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replenishment Report.
        /// </summary>
        public static string ReplenishmentReport {
            get {
                return ResourceManager.GetString("ReplenishmentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replenish Type.
        /// </summary>
        public static string ReplenishmentScheduleType {
            get {
                return ResourceManager.GetString("ReplenishmentScheduleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Percentage.
        /// </summary>
        public static string ReturnPercentage {
            get {
                return ResourceManager.GetString("ReturnPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        public static string Route {
            get {
                return ResourceManager.GetString("Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Combination.
        /// </summary>
        public static string RouteCombination {
            get {
                return ResourceManager.GetString("RouteCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Name.
        /// </summary>
        public static string RouteName {
            get {
                return ResourceManager.GetString("RouteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes.
        /// </summary>
        public static string Routes {
            get {
                return ResourceManager.GetString("Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes Count.
        /// </summary>
        public static string RoutesCount {
            get {
                return ResourceManager.GetString("RoutesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Percentage.
        /// </summary>
        public static string SalesPercentage {
            get {
                return ResourceManager.GetString("SalesPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save And Post.
        /// </summary>
        public static string SaveAndPost {
            get {
                return ResourceManager.GetString("SaveAndPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveOperation.
        /// </summary>
        public static string SaveOperation {
            get {
                return ResourceManager.GetString("SaveOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure.
        /// </summary>
        public static string SaveQuestion {
            get {
                return ResourceManager.GetString("SaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Classification.
        /// </summary>
        public static string SecondClassification {
            get {
                return ResourceManager.GetString("SecondClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select The Day.
        /// </summary>
        public static string SelectTheDay {
            get {
                return ResourceManager.GetString("SelectTheDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select The Month Number.
        /// </summary>
        public static string SelectTheMonthNumber {
            get {
                return ResourceManager.GetString("SelectTheMonthNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select The Order.
        /// </summary>
        public static string SelectTheOrder {
            get {
                return ResourceManager.GetString("SelectTheOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select The Week Number.
        /// </summary>
        public static string SelectTheWeekNumber {
            get {
                return ResourceManager.GetString("SelectTheWeekNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Price.
        /// </summary>
        public static string SellPrice {
            get {
                return ResourceManager.GetString("SellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendingSMSTimeFrom.
        /// </summary>
        public static string SendingSMSTimeFrom {
            get {
                return ResourceManager.GetString("SendingSMSTimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendingSMSTimeTo.
        /// </summary>
        public static string SendingSMSTimeTo {
            get {
                return ResourceManager.GetString("SendingSMSTimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf Life.
        /// </summary>
        public static string ShelfLife {
            get {
                return ResourceManager.GetString("ShelfLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped.
        /// </summary>
        public static string Shipped {
            get {
                return ResourceManager.GetString("Shipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped Date.
        /// </summary>
        public static string ShippedDate {
            get {
                return ResourceManager.GetString("ShippedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped Quantity.
        /// </summary>
        public static string ShippedQty {
            get {
                return ResourceManager.GetString("ShippedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipp The PO.
        /// </summary>
        public static string ShippPO {
            get {
                return ResourceManager.GetString("ShippPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Barcode.
        /// </summary>
        public static string SmallBarcode {
            get {
                return ResourceManager.GetString("SmallBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSNumber.
        /// </summary>
        public static string SMSNumber {
            get {
                return ResourceManager.GetString("SMSNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply Order Number.
        /// </summary>
        public static string SupplyOrderNum {
            get {
                return ResourceManager.GetString("SupplyOrderNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templete.
        /// </summary>
        public static string Templete {
            get {
                return ResourceManager.GetString("Templete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory.
        /// </summary>
        public static string Territory {
            get {
                return ResourceManager.GetString("Territory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Order.
        /// </summary>
        public static string TheOrder {
            get {
                return ResourceManager.GetString("TheOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third.
        /// </summary>
        public static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThirdCalssification.
        /// </summary>
        public static string ThirdCalssification {
            get {
                return ResourceManager.GetString("ThirdCalssification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Customer.
        /// </summary>
        public static string ToStore {
            get {
                return ResourceManager.GetString("ToStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Conversion.
        /// </summary>
        public static string UnitConversion {
            get {
                return ResourceManager.GetString("UnitConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UploadAndSave.
        /// </summary>
        public static string UploadAndSave {
            get {
                return ResourceManager.GetString("UploadAndSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat Number.
        /// </summary>
        public static string VatNumber {
            get {
                return ResourceManager.GetString("VatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisitSchedule.
        /// </summary>
        public static string VisitSchedule {
            get {
                return ResourceManager.GetString("VisitSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Type.
        /// </summary>
        public static string VisitScheduleType {
            get {
                return ResourceManager.GetString("VisitScheduleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Site.
        /// </summary>
        public static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week Number.
        /// </summary>
        public static string WeekNumber {
            get {
                return ResourceManager.GetString("WeekNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (gram).
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
