//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorSystem.Models.Model2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRebateAmount
    {
        public string StoreID { get; set; }
        public string CompanyID { get; set; }
        public string VendorCompanyCode { get; set; }
        public Nullable<decimal> OldRebateAmount { get; set; }
        public Nullable<decimal> NewRebateAmount { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
