//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorSystem.Models.Model2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CentralizedEntities : DbContext
    {
        public CentralizedEntities()
            : base("name=CentralizedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductAttribute> ProductAttributes { get; set; }
        public virtual DbSet<ProductVsDistributor> ProductVsDistributors { get; set; }
        public virtual DbSet<ProductVsVendor> ProductVsVendors { get; set; }
        public virtual DbSet<DistributorVsVendor> DistributorVsVendors { get; set; }
        public virtual DbSet<CustomerRebateAmount> CustomerRebateAmounts { get; set; }
        public virtual DbSet<CentralizedLockUp> CentralizedLockUps { get; set; }
        public virtual DbSet<Customer_URL> Customer_URL { get; set; }
        public virtual DbSet<StoreVsDistributor> StoreVsDistributors { get; set; }
    }
}
