//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorSystem.Models.Model2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVsDistributor
    {
        public string PartnerCode { get; set; }
        public string CompanyID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public string ProductAttrBarcode { get; set; }
        public string InternalCode { get; set; }
    }
}
