//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorSystem.Models.Model2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAttribute
    {
        public decimal Seq { get; set; }
        public decimal Product_Id { get; set; }
        public Nullable<decimal> Color_Id { get; set; }
        public string CompanyID { get; set; }
        public Nullable<decimal> Size_Id { get; set; }
        public Nullable<decimal> MinimumstockQty { get; set; }
        public Nullable<decimal> ReplenishmentQty { get; set; }
        public string BarCode { get; set; }
        public string OldBarCode { get; set; }
        public Nullable<decimal> MappingBarcode { get; set; }
        public decimal Updated { get; set; }
        public decimal Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> Lastupdate { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<int> Deletedby { get; set; }
        public Nullable<int> UOM { get; set; }
        public Nullable<decimal> ParentId { get; set; }
        public Nullable<decimal> MinimumStockLimit { get; set; }
        public Nullable<decimal> MaximumStockLimit { get; set; }
        public Nullable<decimal> ReorderQty { get; set; }
        public Nullable<decimal> MinOrderQty { get; set; }
        public Nullable<decimal> MaxOrderQty { get; set; }
        public string MainSupplier { get; set; }
        public string Manufacturer { get; set; }
    }
}
