//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorSystem.Models.Model2
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreVsDistributor
    {
        public int ID { get; set; }
        public string StoreID { get; set; }
        public string CompanyID { get; set; }
        public string VendorCompanyCode { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> Lastupdate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public string PartnerCode { get; set; }
    }
}
