//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorSystem.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LockUp
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> Lastupdate { get; set; }
        public Nullable<int> Createdby { get; set; }
        public bool Active { get; set; }
        public Nullable<int> Deletedby { get; set; }
        public string Vendor_CompanyID { get; set; }
    }
}
