//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorSystem.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageVSRole
    {
        public decimal ID { get; set; }
        public decimal RoleId { get; set; }
        public decimal PageId { get; set; }
        public bool Search { get; set; }
        public bool Save { get; set; }
        public bool SaveAndPost { get; set; }
        public bool Show { get; set; }
        public bool Print { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Vendor_CompanyID { get; set; }
    }
}
