//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorSystem.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ProductAttribute
    {
        public int ID { get; set; }
        public string Barcode { get; set; }
        public string ChildrenBarcode { get; set; }
        public Nullable<byte> UOM { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string Vendor_CompanyID { get; set; }
    }
}
