//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorSystem.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Company
    {
        public string Vendor_CompanyID { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public string Address { get; set; }
        public string Phone1 { get; set; }
        public string Mobile { get; set; }
        public string Website { get; set; }
        public Nullable<System.DateTime> Lastupdate { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> TerritoryID { get; set; }
        public Nullable<bool> IsCompensationPerPercentage { get; set; }
        public Nullable<int> CompensationValue { get; set; }
        public Nullable<bool> Is_KPI_PerPercentage { get; set; }
        public Nullable<int> KPI_Value { get; set; }
        public Nullable<int> CompensationMonthlyFixedValue { get; set; }
        public string LogURL { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
