//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorSystem.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public string BigBarcode { get; set; }
        public string SmallBarcode { get; set; }
        public int PiecesInCatron { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> FirstClassification { get; set; }
        public Nullable<int> SecondClassification { get; set; }
        public Nullable<int> ThirdClassification { get; set; }
        public Nullable<int> FourthClassification { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public string Vendor_CompanyID { get; set; }
        public Nullable<decimal> ReturnPercentage { get; set; }
        public Nullable<decimal> MinQty { get; set; }
        public Nullable<int> ShelfLifeID { get; set; }
    }
}
