//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorSystem.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CustomerMaster
    {
        public int ID { get; set; }
        public string StoreID { get; set; }
        public string StoreName { get; set; }
        public string StoreNameEng { get; set; }
        public string CompanyID { get; set; }
        public string CompanyNameEng { get; set; }
        public string CompanyName { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string URL { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> TerritoryID { get; set; }
        public string VAT_Registration { get; set; }
        public string Commercial_Registration { get; set; }
        public Nullable<System.DateTime> LastSalesSyncDate { get; set; }
        public Nullable<System.DateTime> LastOpenDay { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
