//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorSystem.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RepConfig_Mstr
    {
        public decimal ID { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public Nullable<int> CalcTypeID { get; set; }
        public Nullable<int> RepScheduleTypeID { get; set; }
        public Nullable<int> RepScheduleCycleCount { get; set; }
        public Nullable<int> VisitScheduleTypeID { get; set; }
        public Nullable<int> VisitScheduleCycleCount { get; set; }
        public Nullable<bool> IsIncludeMinQty { get; set; }
        public Nullable<int> FirstClassID { get; set; }
        public Nullable<int> SecondClassID { get; set; }
        public Nullable<int> ThirdClassID { get; set; }
        public Nullable<int> FourthClassID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string Vendor_CompanyID { get; set; }
    }
}
