//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorSystem.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string User_Name { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<bool> IsManufacture { get; set; }
        public string DistributorCode { get; set; }
        public string Vendor_CompanyID { get; set; }
        public Nullable<bool> IsPasswordHash { get; set; }
    }
}
