//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorSystem.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GetAllRoutesVM
    {
        public int RouteID { get; set; }
        public string Vendor_CompanyID { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public string CountryName { get; set; }
        public string CountryNameEng { get; set; }
        public string CityName { get; set; }
        public string CityNameEng { get; set; }
        public string Note { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> TerritoryID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string RouteCode { get; set; }
    }
}
