//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorSystem.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GetProductCurrentStatus
    {
        public string Vendor_CompanyID { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public string SmallBarcode { get; set; }
        public string BigBarcode { get; set; }
        public string PiecesInCatron { get; set; }
        public string Weight { get; set; }
        public string FirstClassName { get; set; }
        public string FirstClassNameEng { get; set; }
        public string SecondClassName { get; set; }
        public string SecondClassNameEng { get; set; }
        public string ThirdClassName { get; set; }
        public string ThirdClassNameEng { get; set; }
        public string FourthClassName { get; set; }
        public string FourthClassNameEng { get; set; }
        public string EngStatus { get; set; }
        public string ArStatus { get; set; }
        public string ShelfName { get; set; }
        public string ShelfNameEng { get; set; }
        public Nullable<decimal> ReturnPercentage { get; set; }
        public Nullable<decimal> MinQty { get; set; }
    }
}
